final List<String> imagesList = [
  "https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211471.png",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4lTwq_Cb_AwEquAa0B6WNOZCpeZvSiVQq8j7xqw8mJcy-9I4YuIX2lQCPg5w2qaaa42A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTifunhA6ltTu6tVc5-fOv2g7SwTf-dUW89c5Q5eRygq53GmBb1vm5_Kurx-Mg1NwbzREU&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6Fd1i21jAUo6cUoWx4z-4hoiDZXdaww7RNtdKPBpSaawZ_WXB9GKSk-_zMUlHpP6DJ8s&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4D3N0ro9l9Su_CCowsE3gEtPcmcYOyGcyRl4Q4dvi35iWdpm5NlTkON0s3YOOwU4Ph0M&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYu3o3OM1FxYj8x2p9xkWgn_IOypy_wNdy7iGaDVN-uarjlzrTMxHP0mw5uNhJGllhLqs&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa69_HGc_i3MXKCPZzCfAjBZC4bXJsn0rS0Ufe6H-ctZz5FbIVaPkd1jCPTpKwPruIT3Q&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQESjeKHFCxBtOUDr1vB9Xk1dSC1JxReYCj_5VfCmg-boiVNp4JEgrXXjcbhq79QrhHoEc&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo03qI8I9e6YyLjjNryIjw7mJYBIyYmyh7cUfIN_rBCPwgFyrN-piafos4XNhvqrgWjOk&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD8woxjr_40owk1FcTp88hzBeXmJSdJGDcVyDrpQSU_5XkfYm1_JOn0vZ49ANyFeuEtLY&usqp=CAU",
  "https://png.pngtree.com/png-vector/20231019/ourmid/pngtree-user-profile-avatar-png-image_10211471.png",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4lTwq_Cb_AwEquAa0B6WNOZCpeZvSiVQq8j7xqw8mJcy-9I4YuIX2lQCPg5w2qaaa42A&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTifunhA6ltTu6tVc5-fOv2g7SwTf-dUW89c5Q5eRygq53GmBb1vm5_Kurx-Mg1NwbzREU&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6Fd1i21jAUo6cUoWx4z-4hoiDZXdaww7RNtdKPBpSaawZ_WXB9GKSk-_zMUlHpP6DJ8s&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR4D3N0ro9l9Su_CCowsE3gEtPcmcYOyGcyRl4Q4dvi35iWdpm5NlTkON0s3YOOwU4Ph0M&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYu3o3OM1FxYj8x2p9xkWgn_IOypy_wNdy7iGaDVN-uarjlzrTMxHP0mw5uNhJGllhLqs&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa69_HGc_i3MXKCPZzCfAjBZC4bXJsn0rS0Ufe6H-ctZz5FbIVaPkd1jCPTpKwPruIT3Q&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQESjeKHFCxBtOUDr1vB9Xk1dSC1JxReYCj_5VfCmg-boiVNp4JEgrXXjcbhq79QrhHoEc&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo03qI8I9e6YyLjjNryIjw7mJYBIyYmyh7cUfIN_rBCPwgFyrN-piafos4XNhvqrgWjOk&usqp=CAU",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTD8woxjr_40owk1FcTp88hzBeXmJSdJGDcVyDrpQSU_5XkfYm1_JOn0vZ49ANyFeuEtLY&usqp=CAU",
];
final List<String> titleList = [
  "Arslan Tariq",
  "Ali Raza",
  "Usman",
  "Minahil Saddiq",
  "Liaba Rafiq",
  "Ahsan Ahmad",
  "Sohail Shah",
  "Ali Ahmad",
  "Ahmad Raza",
  "Sheraz Fida",
  "Arslan Tariq",
  "Ali Raza",
  "Usman",
  "Minahil Saddiq",
  "Liaba Rafiq",
  "Ahsan Ahmad",
  "Sohail Shah",
  "Ali Ahmad",
  "Ahmad Raza",
  "Sheraz Fida",
];

final List<String> snapList = [
  "1 min ago",
  "5 min ago",
  "7 min ago",
  "1 week ago",
  "1 mon ago",
  "7 min ago",
  "10 min ago",
  "1 mon ago",
  "4 mon ago",
  "6 week ago",
  "1 min ago",
  "5 min ago",
  "7 min ago",
  "1 week ago",
  "1 mon ago",
  "7 min ago",
  "10 min ago",
  "1 mon ago",
  "4 mon ago",
  "6 week ago",
];
